version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - cargo-cache:/root/.cargo
    environment:
      - DATABASE_URL=Manifest.db
    command: watchexec -r -- cargo run

volumes:
  cargo-cache:
